// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "处理WebSocket连接升级请求，建立实时双向通信连接",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "*/*"
                ],
                "tags": [
                    "WebSocket"
                ],
                "summary": "WebSocket连接处理",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID，用于标识客户端设备",
                        "name": "Device-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols - WebSocket连接建立成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request - WebSocket升级失败",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - 服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/asr/docs": {
            "get": {
                "description": "获取ASR系统的完整处理流程文档，包括手动、自动、实时模式和消息类型说明",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "ASR"
                ],
                "summary": "获取ASR处理流程文档",
                "responses": {
                    "200": {
                        "description": "ASR流程文档HTML页面",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/asr/docs/json": {
            "get": {
                "description": "获取ASR系统的完整处理流程文档JSON格式数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ASR"
                ],
                "summary": "获取ASR处理流程文档(JSON)",
                "responses": {
                    "200": {
                        "description": "ASR流程文档JSON数据",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ota/": {
            "get": {
                "description": "获取 OTA 服务状态和 WebSocket 地址，供设备查询",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "OTA"
                ],
                "summary": "获取 OTA 状态",
                "responses": {
                    "200": {
                        "description": "OTA interface is running, websocket address: ws://...",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "设备上传信息后，返回最新固件版本和下载地址",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OTA"
                ],
                "summary": "上传设备信息获取最新固件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ota.OtaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ota.OtaFirmwareResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ota.ErrorResponse"
                        }
                    }
                }
            },
            "options": {
                "description": "处理 OTA 接口的 OPTIONS 预检请求，返回 200",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "OTA"
                ],
                "summary": "OTA 预检请求",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ota_bin/{filename}": {
            "get": {
                "description": "根据文件名下载 OTA 固件",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "OTA"
                ],
                "summary": "下载 OTA 固件文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "固件文件名",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件流"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ota.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ota.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "缺少 device-id"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "ota.OtaFirmwareResponse": {
            "type": "object",
            "properties": {
                "firmware": {
                    "type": "object",
                    "properties": {
                        "url": {
                            "type": "string",
                            "example": "/ota_bin/1.0.3.bin"
                        },
                        "version": {
                            "type": "string",
                            "example": "1.0.3"
                        }
                    }
                },
                "server_time": {
                    "type": "object",
                    "properties": {
                        "timestamp": {
                            "type": "integer",
                            "example": 1688443200000
                        },
                        "timezone_offset": {
                            "type": "integer",
                            "example": 480
                        }
                    }
                },
                "websocket": {
                    "type": "object",
                    "properties": {
                        "url": {
                            "type": "string",
                            "example": "wss://example.com/ota"
                        }
                    }
                }
            }
        },
        "ota.OtaRequest": {
            "type": "object",
            "properties": {
                "application": {
                    "type": "object",
                    "properties": {
                        "version": {
                            "type": "string",
                            "example": "1.0.0"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "怒喵 API 文档",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
