basePath: /api
definitions:
  ota.ErrorResponse:
    properties:
      message:
        example: 缺少 device-id
        type: string
      success:
        example: false
        type: boolean
    type: object
  ota.OtaFirmwareResponse:
    properties:
      firmware:
        properties:
          url:
            example: /ota_bin/1.0.3.bin
            type: string
          version:
            example: 1.0.3
            type: string
        type: object
      server_time:
        properties:
          timestamp:
            example: 1688443200000
            type: integer
          timezone_offset:
            example: 480
            type: integer
        type: object
      websocket:
        properties:
          url:
            example: wss://example.com/ota
            type: string
        type: object
    type: object
  ota.OtaRequest:
    properties:
      application:
        properties:
          version:
            example: 1.0.0
            type: string
        type: object
    type: object
host: localhost:8080
info:
  contact: {}
  title: 怒喵 API 文档
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: 处理WebSocket连接升级请求，建立实时双向通信连接
      parameters:
      - description: 设备ID，用于标识客户端设备
        in: header
        name: Device-Id
        type: string
      produces:
      - '*/*'
      responses:
        "101":
          description: Switching Protocols - WebSocket连接建立成功
          schema:
            type: string
        "400":
          description: Bad Request - WebSocket升级失败
          schema:
            type: string
        "500":
          description: Internal Server Error - 服务器内部错误
          schema:
            type: string
      summary: WebSocket连接处理
      tags:
      - WebSocket
  /api/asr/docs:
    get:
      description: 获取ASR系统的完整处理流程文档，包括手动、自动、实时模式和消息类型说明
      produces:
      - text/html
      responses:
        "200":
          description: ASR流程文档HTML页面
          schema:
            type: string
      summary: 获取ASR处理流程文档
      tags:
      - ASR
  /api/asr/docs/json:
    get:
      description: 获取ASR系统的完整处理流程文档JSON格式数据
      produces:
      - application/json
      responses:
        "200":
          description: ASR流程文档JSON数据
          schema:
            additionalProperties: true
            type: object
      summary: 获取ASR处理流程文档(JSON)
      tags:
      - ASR
  /ota/:
    get:
      description: 获取 OTA 服务状态和 WebSocket 地址，供设备查询
      produces:
      - text/plain
      responses:
        "200":
          description: 'OTA interface is running, websocket address: ws://...'
          schema:
            type: string
      summary: 获取 OTA 状态
      tags:
      - OTA
    options:
      consumes:
      - '*/*'
      description: 处理 OTA 接口的 OPTIONS 预检请求，返回 200
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: OTA 预检请求
      tags:
      - OTA
    post:
      consumes:
      - application/json
      description: 设备上传信息后，返回最新固件版本和下载地址
      parameters:
      - description: 设备ID
        in: header
        name: device-id
        required: true
        type: string
      - description: 请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/ota.OtaRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ota.OtaFirmwareResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ota.ErrorResponse'
      summary: 上传设备信息获取最新固件
      tags:
      - OTA
  /ota_bin/{filename}:
    get:
      description: 根据文件名下载 OTA 固件
      parameters:
      - description: 固件文件名
        in: path
        name: filename
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: 文件流
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ota.ErrorResponse'
      summary: 下载 OTA 固件文件
      tags:
      - OTA
swagger: "2.0"
