services:
  app:
    image: ghcr.io/animeaichat/xiaozhi-server-go:server
    container_name: xiaozhi-server
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: ["./linux-amd64-server-upx"] #修改成程序文件名
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite://./config.db
      - ENV=production
      - PORT=8080
